create table
  public.global_inventory (
    num_red_ml integer not null default 0,
    gold integer not null default 100,
    id bigint generated by default as identity,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.catalog (
    id bigint generated by default as identity,
    sku text not null,
    name text not null,
    price integer not null,
    num_red_ml bigint not null,
    num_green_ml bigint not null,
    num_blue_ml bigint not null,
    num_dark_ml bigint not null,
    quantity integer not null,
    constraint catalog_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    customer_name text not null default ''::text,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    cart_id bigint not null,
    catalog_id bigint not null,
    quantity bigint not null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id) on delete cascade,
    constraint cart_items_catalog_id_fkey foreign key (catalog_id) references catalog (id) on delete cascade
  ) tablespace pg_default;